import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { initializeFirestore, persistentLocalCache, collection, doc, setDoc, addDoc, deleteDoc, onSnapshot, query, orderBy, limit, getDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';

// Firebase web config. The measurement ID is optional for this Firestore-only app.
const firebaseConfig = {
  apiKey: "AIzaSyDoY2Pf_u3C_o1eBKQwmEymJgraIaZcffY",
  authDomain: "workout-app-ed738.firebaseapp.com",
  projectId: "workout-app-ed738",
  storageBucket: "workout-app-ed738.firebasestorage.app",
  messagingSenderId: "1083241132824",
  appId: "1:1083241132824:web:595f0ccf8114e30d52a46d",
  measurementId: "G-PWEDH51MWD"
};
const configured = !firebaseConfig.apiKey.startsWith('PASTE_');
const $ = (selector, root = document) => root.querySelector(selector);
const today = () => new Date().toISOString().slice(0, 10);
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const fmtDate = value => value ? new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { month:'short', day:'numeric', year:'numeric' }) : 'No date';
const uid = () => crypto.randomUUID();
let db, keyHash, root, unsubscribers = [], state = { settings: { macroGoals: { calories: 2200, proteinG: 160, carbsG: 220, fatG: 70 }, weightUnit: 'lb', restTimerSeconds: 90 }, routines: [], workouts: [], activities: [], diet: [], goalHistory: [] };

async function hashKey(key) { const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(key)); return [...new Uint8Array(bytes)].map(byte => byte.toString(16).padStart(2, '0')).join(''); }
async function getSyncKey() { let key = localStorage.getItem('formFuelSyncKey'); if (!key) { key = prompt('Choose a Sync Key. Use a memorable, hard-to-guess passphrase:'); if (!key?.trim()) return null; localStorage.setItem('formFuelSyncKey', key.trim()); } return hashKey(key); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2400); }
function col(name) { return collection(root, name); }
async function saveSettings(patch) { state.settings = { ...state.settings, ...patch }; await setDoc(doc(root, 'meta', 'settings'), state.settings, { merge: true }); }
async function write(collectionName, data, id = uid()) { if (!configured) { state[collectionName] = [{ id, ...data }, ...state[collectionName]]; render(); return; } await setDoc(doc(col(collectionName), id), { ...data, updatedAt: serverTimestamp() }); }
async function remove(collectionName, id) { if (!configured) { state[collectionName] = state[collectionName].filter(item => item.id !== id); render(); return; } await deleteDoc(doc(col(collectionName), id)); }
function listen(name, options = {}) { if (!configured) return; const source = col(name); const q = options.orderBy === false ? query(source, limit(options.limit || 50)) : query(source, orderBy(options.orderBy || 'date', 'desc'), limit(options.limit || 50)); unsubscribers.push(onSnapshot(q, snap => { state[name] = snap.docs.map(item => ({ id: item.id, ...item.data() })); render(); })); }
function field(label, name, type = 'number', value = '') { return `<div class="field"><label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label></div>`; }
function routineForm(routine = {}) { const exercises = routine.exercises || [{ id: uid(), name:'', targetSets:3, targetReps:8 }]; return `<form id="routineForm" class="card"><input type="hidden" name="id" value="${esc(routine.id || '')}"><div class="section-head"><h2>${routine.id ? 'Edit routine' : 'New routine'}</h2><button type="button" class="button ghost small" id="addExercise">+ Exercise</button></div>${field('Routine name','name','text',routine.name || '')}<div id="exerciseFields">${exercises.map(ex => `<div class="exercise"><div class="field"><label>Exercise<input name="exerciseName" value="${esc(ex.name)}" required></label></div><div class="field"><label>Sets<input name="targetSets" type="number" min="1" value="${ex.targetSets || 3}" required></label></div><div class="field"><label>Reps<input name="targetReps" type="number" min="1" value="${ex.targetReps || 8}" required></label></div><button type="button" class="icon-button remove-exercise" aria-label="Remove exercise">×</button></div>`).join('')}</div><button class="button">Save routine</button></form>`; }
function renderRoutines() { $('#routines').innerHTML = `<div class="grid routine-layout"><div><div class="section-head"><div><p class="eyebrow">TRAIN WITH INTENT</p><h2>Routines</h2></div><button class="button" id="newRoutine">+ New routine</button></div><div class="list">${state.routines.length ? state.routines.map(r => `<article class="card"><div class="section-head"><div><h3>${esc(r.name)}</h3><p class="muted">${r.exercises?.length || 0} exercises</p></div><div class="actions"><button class="button small log-workout" data-id="${r.id}">Log workout</button><button class="button ghost small edit-routine" data-id="${r.id}">Edit</button><button class="button danger small delete-routine" data-id="${r.id}">Delete</button></div></div><p>${(r.exercises || []).map(ex => `<span class="tag">${esc(ex.name)} · ${ex.targetSets} × ${ex.targetReps}</span>`).join(' ')}</p></article>`).join('') : '<div class="card empty">No routines yet. Build your first one.</div>'}</div></div><div id="routineEditor"></div></div>`; $('#newRoutine').onclick = () => { $('#routineEditor').innerHTML = routineForm(); wireRoutineForm(); }; document.querySelectorAll('.edit-routine').forEach(btn => btn.onclick = () => { const routine = state.routines.find(item => item.id === btn.dataset.id); $('#routineEditor').innerHTML = routineForm(routine); wireRoutineForm(); }); document.querySelectorAll('.delete-routine').forEach(btn => btn.onclick = () => remove('routines', btn.dataset.id)); document.querySelectorAll('.log-workout').forEach(btn => btn.onclick = () => logWorkout(btn.dataset.id)); }
async function logWorkout(routineId) { const routine = state.routines.find(item => item.id === routineId); if (!routine) return; const entries = routine.exercises.map(exercise => { const rawSets = prompt(`${exercise.name}: enter sets as reps@weight, separated by commas (example: 8@135, 8@135)`); if (!rawSets) return null; const sets = rawSets.split(',').map(value => { const [reps, weight] = value.trim().split('@'); return { reps:Number(reps) || 0, weight:Number(weight) || 0, unit:state.settings.weightUnit }; }); return { exerciseId:exercise.id, exerciseName:exercise.name, sets }; }).filter(Boolean); if (!entries.length) return; await write('workouts', { date:today(), routineId, routineName:routine.name, entries }); toast('Workout logged'); }
function wireRoutineForm() { const form = $('#routineForm'); if (!form) return; $('#addExercise').onclick = () => { const wrapper = document.createElement('div'); wrapper.innerHTML = `<div class="exercise"><div class="field"><label>Exercise<input name="exerciseName" required></label></div><div class="field"><label>Sets<input name="targetSets" type="number" min="1" value="3" required></label></div><div class="field"><label>Reps<input name="targetReps" type="number" min="1" value="8" required></label></div><button type="button" class="icon-button remove-exercise">×</button></div>`; $('#exerciseFields').append(wrapper.firstElementChild); wireRemoveButtons(); }; wireRemoveButtons(); form.onsubmit = async event => { event.preventDefault(); const data = new FormData(form); const names = data.getAll('exerciseName'); const sets = data.getAll('targetSets'); const reps = data.getAll('targetReps'); const id = data.get('id') || uid(); await write('routines', { name: data.get('name'), exercises: names.map((name, i) => ({ id: uid(), name, targetSets: Number(sets[i]), targetReps: Number(reps[i]) })) }, id); toast('Routine saved'); $('#routineEditor').innerHTML = ''; }; }
function wireRemoveButtons() { document.querySelectorAll('.remove-exercise').forEach(btn => btn.onclick = () => btn.closest('.exercise').remove()); }
function renderActivity() { const recent = [...state.workouts, ...state.activities].sort((a,b) => String(b.date).localeCompare(String(a.date))).slice(0, 50); $('#activity').innerHTML = `<div class="grid two-col"><div><div class="section-head"><div><p class="eyebrow">DAILY ACTION LOG</p><h2>Activity</h2></div></div><div class="card"><h3>Log a non-workout activity</h3><form id="activityForm">${field('Type','type','text','Run')}${field('Date','date','date',today())}${field('Duration (minutes)','durationMin','number',30)}${field('Estimated calories (optional)','caloriesEst','number','')}<div class="field"><label>Notes<textarea name="notes" placeholder="How did it feel?"></textarea></label></div><button class="button">Log activity</button></form></div></div><div><h2>Recent movement</h2><div class="list">${recent.length ? recent.map(item => `<article class="card list-item"><div><strong>${esc(item.type || 'Workout')}</strong><p class="muted">${fmtDate(item.date)} · ${item.durationMin ? `${item.durationMin} min` : `${item.entries?.length || 0} exercises`}</p></div><button class="button danger small delete-item" data-kind="${item.entries ? 'workouts' : 'activities'}" data-id="${item.id}">Delete</button></article>`).join('') : '<div class="card empty">Your movement log is waiting.</div>'}</div></div></div>`; $('#activityForm').onsubmit = async e => { e.preventDefault(); const data = new FormData(e.target); await write('activities', { date:data.get('date'), type:data.get('type'), durationMin:Number(data.get('durationMin')), notes:data.get('notes'), caloriesEst:Number(data.get('caloriesEst')) || null }); e.target.reset(); toast('Activity logged'); }; document.querySelectorAll('.delete-item').forEach(btn => btn.onclick = () => remove(btn.dataset.kind, btn.dataset.id)); }
function renderDiet() { const day = state.diet.find(item => item.id === today()) || { meals: [], totals:{ calories:0, proteinG:0, carbsG:0, fatG:0 } }; const goals = state.settings.macroGoals; $('#diet').innerHTML = `<div class="grid two-col"><div><div class="section-head"><div><p class="eyebrow">NOURISH THE WORK</p><h2>Diet</h2></div></div><div class="card"><h3>Today's totals</h3><div class="metric-row">${[['Calories','calories'],['Protein','proteinG'],['Carbs','carbsG'],['Fat','fatG']].map(([label,key]) => `<div class="metric"><strong>${Math.round(day.totals?.[key] || 0)}</strong><small>${label} / ${goals[key] || 0}</small><div class="progress"><i style="width:${Math.min(100,((day.totals?.[key] || 0)/(goals[key] || 1))*100)}%"></i></div></div>`).join('')}</div><hr><h3>Add meal</h3><form id="mealForm">${field('Meal or food','name','text','')}${field('Calories','calories','number',500)}<div class="grid two-col">${field('Protein (g)','proteinG','number',30)}${field('Carbs (g)','carbsG','number',50)}${field('Fat (g)','fatG','number',15)}</div><button class="button">Add meal</button></form></div></div><div><div class="card"><div class="section-head"><h3>Today's meals</h3><span class="tag">${fmtDate(today())}</span></div><div class="list">${day.meals?.length ? day.meals.map(meal => `<div class="list-item"><span><strong>${esc(meal.name)}</strong><br><small class="muted">${meal.calories} cal · ${meal.proteinG}g protein</small></span></div>`).join('') : '<p class="empty">No meals logged yet.</p>'}</div></div><div class="card"><h3>Active macro goals</h3><form id="goalsForm"><div class="grid two-col">${field('Calories','calories','number',goals.calories)}${field('Protein (g)','proteinG','number',goals.proteinG)}${field('Carbs (g)','carbsG','number',goals.carbsG)}${field('Fat (g)','fatG','number',goals.fatG)}</div><button class="button">Update goals</button></form></div></div></div>`; $('#mealForm').onsubmit = async e => { e.preventDefault(); const data = new FormData(e.target); const meal = { name:data.get('name'), calories:Number(data.get('calories')), proteinG:Number(data.get('proteinG')), carbsG:Number(data.get('carbsG')), fatG:Number(data.get('fatG')) }; const meals = [...(day.meals || []), meal]; const totals = meals.reduce((sum,item) => Object.fromEntries(Object.keys(sum).map(key => [key, sum[key] + Number(item[key] || 0)])), { calories:0, proteinG:0, carbsG:0, fatG:0 }); await write('diet', { date:today(), meals, totals }, today()); toast('Meal added'); }; $('#goalsForm').onsubmit = async e => { e.preventDefault(); const data = new FormData(e.target); const macroGoals = Object.fromEntries(['calories','proteinG','carbsG','fatG'].map(key => [key, Number(data.get(key))])); await saveSettings({ macroGoals }); await write('goalHistory', { date:today(), macroGoals }); toast('Goals updated'); }; }
function renderHistory() { const items = [...state.workouts.map(item => ({ ...item, kind:'Workout', title:item.routineName || 'Completed workout' })), ...state.activities.map(item => ({ ...item, kind:'Activity', title:item.type })), ...state.diet.map(item => ({ ...item, kind:'Diet', title:`${item.totals?.calories || 0} calorie day` }))].sort((a,b) => String(b.date).localeCompare(String(a.date))).slice(0,50); $('#history').innerHTML = `<div class="section-head"><div><p class="eyebrow">THE RECEIPTS</p><h2>History</h2><p class="muted">Your last 50 logged moments, across movement and nutrition.</p></div></div><div class="list">${items.length ? items.map(item => `<article class="card list-item"><div><span class="tag">${item.kind}</span><h3>${esc(item.title)}</h3><p class="muted">${fmtDate(item.date)}${item.durationMin ? ` · ${item.durationMin} min` : ''}</p></div><details><summary>Details</summary><pre>${esc(JSON.stringify(item, null, 2))}</pre></details></article>`).join('') : '<div class="card empty">Complete a workout, activity, or meal to start your history.</div>'}</div>`; }
function render() { renderRoutines(); renderActivity(); renderDiet(); renderHistory(); }
async function start() { if (!configured) { $('#setupNotice').textContent = 'Demo mode: paste your Firebase web config into app.js to enable cross-device sync. Local interactions still work in this browser.'; $('#setupNotice').classList.remove('hidden'); render(); return; } keyHash = await getSyncKey(); if (!keyHash) return; root = doc(db, 'syncKeys', keyHash); const settings = await getDoc(doc(root, 'meta', 'settings')); if (settings.exists()) state.settings = { ...state.settings, ...settings.data() }; listen('routines', { orderBy:false, limit:50 }); ['workouts','activities','diet','goalHistory'].forEach(name => listen(name, { orderBy:'date', limit:50 })); render(); }
function setupUi() { document.querySelectorAll('.tab').forEach(tab => tab.onclick = () => { document.querySelectorAll('.tab,.page').forEach(el => el.classList.remove('active')); tab.classList.add('active'); $(`#${tab.dataset.page}`).classList.add('active'); }); $('#settingsButton').onclick = () => { $('#weightUnit').value = state.settings.weightUnit; $('#restSeconds').value = state.settings.restTimerSeconds; $('#settingsDialog').showModal(); }; $('#settingsForm').onsubmit = async e => { if (e.submitter?.value !== 'save') return; await saveSettings({ weightUnit:$('#weightUnit').value, restTimerSeconds:Number($('#restSeconds').value) }); toast('Settings saved'); }; $('#changeKey').onclick = () => { localStorage.removeItem('formFuelSyncKey'); location.reload(); }; }
if (configured) db = initializeFirestore(initializeApp(firebaseConfig), { localCache: persistentLocalCache() });
setupUi(); start();
if ('serviceWorker' in navigator && location.protocol !== 'file:') navigator.serviceWorker.register('service-worker.js').catch(() => {});
